version: "3"
services:
  typesense-client:
    image: typesense/typesense:${TYPESENSE_VERSION}
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=${TYPESENSE_CLIENT_API_KEY} --enable-cors"
    ports:
      - "${TYPESENSE_PORT_CLIENT}:8108"
    volumes:
      - typesense-client-data:/data
  typesense-admin:
    image: typesense/typesense:${TYPESENSE_VERSION}
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=${TYPESENSE_ADMIN_API_KEY} --enable-cors"
    ports:
      - "${TYPESENSE_PORT_ADMIN}:8108"
    volumes:
      - typesense-admin-data:/data
volumes:
  typesense-admin-data:
    driver: local
  typesense-client-data:
    driver: local
